import web

class Footer:
    def get_footer(self):
        result = '<html><head><title>Test Groupe 02</title>'
        result +='<style>'
        result +='footer{font-size: 18px; background: linear-gradient(414deg, #053e3a 0%, #1fc8db 51%, #2cb5e8 75%);padding: 10px;color: white;font-family:Calibri, sans-serif;margin-top:0px;}'
        result +='a:link, a:visited {color: white;padding: 2px;text-align: center;text-decoration: none;display: inline-block;}'
        result +='a:hover, a:active {background-color: #053e3a;}'
        result +='.navigation ul{list-style-type: none;text-decoration: none; justify-content: space-around; align-items: end;}'
        result +='#ensemble{display: flex;justify-content: space-evenly;}'
        result +='#Copyright{text-align: center;text-decoration: none; }'
        result +='hr{color: aquamarine;}'
        result +='</style>'
        result +='</head>'
        result +='<footer>'
        result +='<div id="ensemble">'
        result +='<h1>EXAMEN</h1>'
        result +='<div class="navigation">'
        result +='<ul>'
        result +='<p>USEFUL LINK</p>'
        result +='<li><a href="/">Home</a></li>'
        result +='<li><a href="/album">Albums</a></li>'
        result +='<li><a href="/artist">Artists</a></li>'
        result +='<li><a href="/genre">Genre</a></li>'
        result +='<li><a href="/employee">Employee</a></li>'
        result +='<li><a href="/customer">Customer</a></li>'
        result +='<li><a href="/playlist">Playlist</a></li>'
        result +='<li><a href="/invoice">Invoice</a></li>'
        result +='<li><a href="/invoiceLine">InvoiceLine</a></li>'
        result +='<li><a href="/mediaType">MediaType</a></li>'
        result +='</ul>'
        result +='</div>'
        result +='<div id="adresse">'
        result +='<p>ADRESS</p>'
        result +='<p>INSI</p>'
        result +='<p>Lot VF 32 Ter Ankazotokana Ambanidia</p>'
        result +='</div>'
        result +='<div id="contact">'
        result +='<p>CONTACT</p>'
        result +='<p>Gmail: exemplecontact@gmail.com</p>'
        result +='<p>Telephone: +261 ## ## ### ##</p>'
        result +='<p>Facebook: Exemple de page</p>'
        result +='</div>'
        result +='</div>'
        result +='<hr>'
        result +='<div id="Copyright">'
        result +='<p>Créé par <strong>le Groupe 02</strong>'
        result +='<p>Copyright 2023, Multimedia management </p>'
        result +='</div>'
        result +='</footer>'
        return result